/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessibilidadeRouteImport } from './routes/acessibilidade'
import { Route as AutorizacaoCondominioRouteImport } from './routes/autorizacao-condominio'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as EscopoRouteImport } from './routes/escopo'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GuiaDoInvestidorRouteImport } from './routes/guia-do-investidor'
import { Route as IndiqueUmAmigoRouteImport } from './routes/indique-um-amigo'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MapaDoSiteRouteImport } from './routes/mapa-do-site'
import { Route as MarcasEParceriasRouteImport } from './routes/marcas-e-parcerias'
import { Route as MarcenariaRouteImport } from './routes/marcenaria'
import { Route as ORouteImport } from './routes/o'
import { Route as OndeAtuamosRouteImport } from './routes/onde-atuamos'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as PRouteImport } from './routes/p'
import { Route as PreferenciasDeCookiesRouteImport } from './routes/preferencias-de-cookies'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ReformaDeApartamentoSaoPauloRouteImport } from './routes/reforma-de-apartamento-sao-paulo'
import { Route as ReformaDeCoberturaSaoPauloRouteImport } from './routes/reforma-de-cobertura-sao-paulo'
import { Route as ReformaDeStudioSaoPauloRouteImport } from './routes/reforma-de-studio-sao-paulo'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCentralRouteImport } from './routes/admin.central'
import { Route as AdminConversoesRouteImport } from './routes/admin.conversoes'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDiagnosticoRouteImport } from './routes/admin.diagnostico'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminIndexacaoRouteImport } from './routes/admin.indexacao'
import { Route as AdminIndicacoesRouteImport } from './routes/admin.indicacoes'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLgpdRouteImport } from './routes/admin.lgpd'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMensagensRouteImport } from './routes/admin.mensagens'
import { Route as AdminOrcamentosRouteImport } from './routes/admin.orcamentos'
import { Route as AdminQualificacaoRouteImport } from './routes/admin.qualificacao'
import { Route as AdminRastreamentoRouteImport } from './routes/admin.rastreamento'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTypographyRouteImport } from './routes/admin.typography'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ConteudosIndexRouteImport } from './routes/conteudos.index'
import { Route as ConteudosSlugRouteImport } from './routes/conteudos.$slug'
import { Route as ParceirosIndexRouteImport } from './routes/parceiros.index'
import { Route as ParceirosIncorporadorasRouteImport } from './routes/parceiros.incorporadoras'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ReformaSlugRouteImport } from './routes/reforma.$slug'
import { Route as AdminBewildIndexRouteImport } from './routes/admin.bewild.index'
import { Route as AdminBewildSlugRouteImport } from './routes/admin.bewild.$slug'
import { Route as AdminBewildNewRouteImport } from './routes/admin.bewild.new'
import { Route as AdminConteudosIndexRouteImport } from './routes/admin.conteudos.index'
import { Route as AdminConteudosSlugRouteImport } from './routes/admin.conteudos.$slug'
import { Route as AdminConteudosNovoRouteImport } from './routes/admin.conteudos.novo'
import { Route as AdminProjetosIndexRouteImport } from './routes/admin.projetos.index'
import { Route as AdminProjetosSlugRouteImport } from './routes/admin.projetos.$slug'
import { Route as AdminProjetosNovoRouteImport } from './routes/admin.projetos.novo'
import { Route as AdminSeoIndexRouteImport } from './routes/admin.seo.index'
import { Route as AdminSeo404RouteImport } from './routes/admin.seo.404'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessibilidadeRoute = AcessibilidadeRouteImport.update({
  id: '/acessibilidade',
  path: '/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorizacaoCondominioRoute = AutorizacaoCondominioRouteImport.update({
  id: '/autorizacao-condominio',
  path: '/autorizacao-condominio',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const EscopoRoute = EscopoRouteImport.update({
  id: '/escopo',
  path: '/escopo',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDoInvestidorRoute = GuiaDoInvestidorRouteImport.update({
  id: '/guia-do-investidor',
  path: '/guia-do-investidor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiqueUmAmigoRoute = IndiqueUmAmigoRouteImport.update({
  id: '/indique-um-amigo',
  path: '/indique-um-amigo',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaDoSiteRoute = MapaDoSiteRouteImport.update({
  id: '/mapa-do-site',
  path: '/mapa-do-site',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasEParceriasRoute = MarcasEParceriasRouteImport.update({
  id: '/marcas-e-parcerias',
  path: '/marcas-e-parcerias',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcenariaRoute = MarcenariaRouteImport.update({
  id: '/marcenaria',
  path: '/marcenaria',
  getParentRoute: () => rootRouteImport,
} as any)
const ORoute = ORouteImport.update({
  id: '/o',
  path: '/o',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeAtuamosRoute = OndeAtuamosRouteImport.update({
  id: '/onde-atuamos',
  path: '/onde-atuamos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PRoute = PRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferenciasDeCookiesRoute = PreferenciasDeCookiesRouteImport.update({
  id: '/preferencias-de-cookies',
  path: '/preferencias-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformaDeApartamentoSaoPauloRoute =
  ReformaDeApartamentoSaoPauloRouteImport.update({
    id: '/reforma-de-apartamento-sao-paulo',
    path: '/reforma-de-apartamento-sao-paulo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReformaDeCoberturaSaoPauloRoute =
  ReformaDeCoberturaSaoPauloRouteImport.update({
    id: '/reforma-de-cobertura-sao-paulo',
    path: '/reforma-de-cobertura-sao-paulo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReformaDeStudioSaoPauloRoute = ReformaDeStudioSaoPauloRouteImport.update({
  id: '/reforma-de-studio-sao-paulo',
  path: '/reforma-de-studio-sao-paulo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCentralRoute = AdminCentralRouteImport.update({
  id: '/admin/central',
  path: '/admin/central',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversoesRoute = AdminConversoesRouteImport.update({
  id: '/admin/conversoes',
  path: '/admin/conversoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticoRoute = AdminDiagnosticoRouteImport.update({
  id: '/admin/diagnostico',
  path: '/admin/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/admin/faq',
  path: '/admin/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexacaoRoute = AdminIndexacaoRouteImport.update({
  id: '/admin/indexacao',
  path: '/admin/indexacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndicacoesRoute = AdminIndicacoesRouteImport.update({
  id: '/admin/indicacoes',
  path: '/admin/indicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/admin/integracoes',
  path: '/admin/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLgpdRoute = AdminLgpdRouteImport.update({
  id: '/admin/lgpd',
  path: '/admin/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMensagensRoute = AdminMensagensRouteImport.update({
  id: '/admin/mensagens',
  path: '/admin/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrcamentosRoute = AdminOrcamentosRouteImport.update({
  id: '/admin/orcamentos',
  path: '/admin/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQualificacaoRoute = AdminQualificacaoRouteImport.update({
  id: '/admin/qualificacao',
  path: '/admin/qualificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRastreamentoRoute = AdminRastreamentoRouteImport.update({
  id: '/admin/rastreamento',
  path: '/admin/rastreamento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTypographyRoute = AdminTypographyRouteImport.update({
  id: '/admin/typography',
  path: '/admin/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosIndexRoute = ConteudosIndexRouteImport.update({
  id: '/conteudos/',
  path: '/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosSlugRoute = ConteudosSlugRouteImport.update({
  id: '/conteudos/$slug',
  path: '/conteudos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosIndexRoute = ParceirosIndexRouteImport.update({
  id: '/parceiros/',
  path: '/parceiros/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosIncorporadorasRoute = ParceirosIncorporadorasRouteImport.update({
  id: '/parceiros/incorporadoras',
  path: '/parceiros/incorporadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReformaSlugRoute = ReformaSlugRouteImport.update({
  id: '/reforma/$slug',
  path: '/reforma/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBewildIndexRoute = AdminBewildIndexRouteImport.update({
  id: '/admin/bewild/',
  path: '/admin/bewild/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBewildSlugRoute = AdminBewildSlugRouteImport.update({
  id: '/admin/bewild/$slug',
  path: '/admin/bewild/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBewildNewRoute = AdminBewildNewRouteImport.update({
  id: '/admin/bewild/new',
  path: '/admin/bewild/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosIndexRoute = AdminConteudosIndexRouteImport.update({
  id: '/admin/conteudos/',
  path: '/admin/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosSlugRoute = AdminConteudosSlugRouteImport.update({
  id: '/admin/conteudos/$slug',
  path: '/admin/conteudos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosNovoRoute = AdminConteudosNovoRouteImport.update({
  id: '/admin/conteudos/novo',
  path: '/admin/conteudos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetosIndexRoute = AdminProjetosIndexRouteImport.update({
  id: '/admin/projetos/',
  path: '/admin/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetosSlugRoute = AdminProjetosSlugRouteImport.update({
  id: '/admin/projetos/$slug',
  path: '/admin/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetosNovoRoute = AdminProjetosNovoRouteImport.update({
  id: '/admin/projetos/novo',
  path: '/admin/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoIndexRoute = AdminSeoIndexRouteImport.update({
  id: '/admin/seo/',
  path: '/admin/seo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeo404Route = AdminSeo404RouteImport.update({
  id: '/admin/seo/404',
  path: '/admin/seo/404',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/autorizacao-condominio': typeof AutorizacaoCondominioRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/escopo': typeof EscopoRoute
  '/faq': typeof FaqRoute
  '/guia-do-investidor': typeof GuiaDoInvestidorRoute
  '/indique-um-amigo': typeof IndiqueUmAmigoRoute
  '/mapa': typeof MapaRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/marcas-e-parcerias': typeof MarcasEParceriasRoute
  '/marcenaria': typeof MarcenariaRoute
  '/o': typeof ORoute
  '/onde-atuamos': typeof OndeAtuamosRoute
  '/orcamento': typeof OrcamentoRoute
  '/p': typeof PRoute
  '/preferencias-de-cookies': typeof PreferenciasDeCookiesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reforma-de-apartamento-sao-paulo': typeof ReformaDeApartamentoSaoPauloRoute
  '/reforma-de-cobertura-sao-paulo': typeof ReformaDeCoberturaSaoPauloRoute
  '/reforma-de-studio-sao-paulo': typeof ReformaDeStudioSaoPauloRoute
  '/servicos': typeof ServicosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/central': typeof AdminCentralRoute
  '/admin/conversoes': typeof AdminConversoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/indexacao': typeof AdminIndexacaoRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lgpd': typeof AdminLgpdRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/qualificacao': typeof AdminQualificacaoRoute
  '/admin/rastreamento': typeof AdminRastreamentoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/typography': typeof AdminTypographyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/parceiros/incorporadoras': typeof ParceirosIncorporadorasRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/reforma/$slug': typeof ReformaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/parceiros/': typeof ParceirosIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/bewild/$slug': typeof AdminBewildSlugRoute
  '/admin/bewild/new': typeof AdminBewildNewRoute
  '/admin/conteudos/$slug': typeof AdminConteudosSlugRoute
  '/admin/conteudos/novo': typeof AdminConteudosNovoRoute
  '/admin/projetos/$slug': typeof AdminProjetosSlugRoute
  '/admin/projetos/novo': typeof AdminProjetosNovoRoute
  '/admin/seo/404': typeof AdminSeo404Route
  '/admin/bewild/': typeof AdminBewildIndexRoute
  '/admin/conteudos/': typeof AdminConteudosIndexRoute
  '/admin/projetos/': typeof AdminProjetosIndexRoute
  '/admin/seo/': typeof AdminSeoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/autorizacao-condominio': typeof AutorizacaoCondominioRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/escopo': typeof EscopoRoute
  '/faq': typeof FaqRoute
  '/guia-do-investidor': typeof GuiaDoInvestidorRoute
  '/indique-um-amigo': typeof IndiqueUmAmigoRoute
  '/mapa': typeof MapaRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/marcas-e-parcerias': typeof MarcasEParceriasRoute
  '/marcenaria': typeof MarcenariaRoute
  '/o': typeof ORoute
  '/onde-atuamos': typeof OndeAtuamosRoute
  '/orcamento': typeof OrcamentoRoute
  '/p': typeof PRoute
  '/preferencias-de-cookies': typeof PreferenciasDeCookiesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reforma-de-apartamento-sao-paulo': typeof ReformaDeApartamentoSaoPauloRoute
  '/reforma-de-cobertura-sao-paulo': typeof ReformaDeCoberturaSaoPauloRoute
  '/reforma-de-studio-sao-paulo': typeof ReformaDeStudioSaoPauloRoute
  '/servicos': typeof ServicosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/central': typeof AdminCentralRoute
  '/admin/conversoes': typeof AdminConversoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/indexacao': typeof AdminIndexacaoRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lgpd': typeof AdminLgpdRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/qualificacao': typeof AdminQualificacaoRoute
  '/admin/rastreamento': typeof AdminRastreamentoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/typography': typeof AdminTypographyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/parceiros/incorporadoras': typeof ParceirosIncorporadorasRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/reforma/$slug': typeof ReformaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/conteudos': typeof ConteudosIndexRoute
  '/parceiros': typeof ParceirosIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/admin/bewild/$slug': typeof AdminBewildSlugRoute
  '/admin/bewild/new': typeof AdminBewildNewRoute
  '/admin/conteudos/$slug': typeof AdminConteudosSlugRoute
  '/admin/conteudos/novo': typeof AdminConteudosNovoRoute
  '/admin/projetos/$slug': typeof AdminProjetosSlugRoute
  '/admin/projetos/novo': typeof AdminProjetosNovoRoute
  '/admin/seo/404': typeof AdminSeo404Route
  '/admin/bewild': typeof AdminBewildIndexRoute
  '/admin/conteudos': typeof AdminConteudosIndexRoute
  '/admin/projetos': typeof AdminProjetosIndexRoute
  '/admin/seo': typeof AdminSeoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/autorizacao-condominio': typeof AutorizacaoCondominioRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/escopo': typeof EscopoRoute
  '/faq': typeof FaqRoute
  '/guia-do-investidor': typeof GuiaDoInvestidorRoute
  '/indique-um-amigo': typeof IndiqueUmAmigoRoute
  '/mapa': typeof MapaRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/marcas-e-parcerias': typeof MarcasEParceriasRoute
  '/marcenaria': typeof MarcenariaRoute
  '/o': typeof ORoute
  '/onde-atuamos': typeof OndeAtuamosRoute
  '/orcamento': typeof OrcamentoRoute
  '/p': typeof PRoute
  '/preferencias-de-cookies': typeof PreferenciasDeCookiesRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reforma-de-apartamento-sao-paulo': typeof ReformaDeApartamentoSaoPauloRoute
  '/reforma-de-cobertura-sao-paulo': typeof ReformaDeCoberturaSaoPauloRoute
  '/reforma-de-studio-sao-paulo': typeof ReformaDeStudioSaoPauloRoute
  '/servicos': typeof ServicosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/central': typeof AdminCentralRoute
  '/admin/conversoes': typeof AdminConversoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/indexacao': typeof AdminIndexacaoRoute
  '/admin/indicacoes': typeof AdminIndicacoesRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lgpd': typeof AdminLgpdRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/qualificacao': typeof AdminQualificacaoRoute
  '/admin/rastreamento': typeof AdminRastreamentoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/typography': typeof AdminTypographyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/parceiros/incorporadoras': typeof ParceirosIncorporadorasRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/reforma/$slug': typeof ReformaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/parceiros/': typeof ParceirosIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/bewild/$slug': typeof AdminBewildSlugRoute
  '/admin/bewild/new': typeof AdminBewildNewRoute
  '/admin/conteudos/$slug': typeof AdminConteudosSlugRoute
  '/admin/conteudos/novo': typeof AdminConteudosNovoRoute
  '/admin/projetos/$slug': typeof AdminProjetosSlugRoute
  '/admin/projetos/novo': typeof AdminProjetosNovoRoute
  '/admin/seo/404': typeof AdminSeo404Route
  '/admin/bewild/': typeof AdminBewildIndexRoute
  '/admin/conteudos/': typeof AdminConteudosIndexRoute
  '/admin/projetos/': typeof AdminProjetosIndexRoute
  '/admin/seo/': typeof AdminSeoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessibilidade'
    | '/autorizacao-condominio'
    | '/como-funciona'
    | '/contato'
    | '/diagnostico'
    | '/escopo'
    | '/faq'
    | '/guia-do-investidor'
    | '/indique-um-amigo'
    | '/mapa'
    | '/mapa-do-site'
    | '/marcas-e-parcerias'
    | '/marcenaria'
    | '/o'
    | '/onde-atuamos'
    | '/orcamento'
    | '/p'
    | '/preferencias-de-cookies'
    | '/privacidade'
    | '/reforma-de-apartamento-sao-paulo'
    | '/reforma-de-cobertura-sao-paulo'
    | '/reforma-de-studio-sao-paulo'
    | '/servicos'
    | '/admin/analytics'
    | '/admin/central'
    | '/admin/conversoes'
    | '/admin/dashboard'
    | '/admin/diagnostico'
    | '/admin/faq'
    | '/admin/indexacao'
    | '/admin/indicacoes'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/lgpd'
    | '/admin/login'
    | '/admin/mensagens'
    | '/admin/orcamentos'
    | '/admin/qualificacao'
    | '/admin/rastreamento'
    | '/admin/settings'
    | '/admin/typography'
    | '/blog/$slug'
    | '/conteudos/$slug'
    | '/parceiros/incorporadoras'
    | '/portfolio/$slug'
    | '/reforma/$slug'
    | '/admin/'
    | '/blog/'
    | '/conteudos/'
    | '/parceiros/'
    | '/portfolio/'
    | '/admin/bewild/$slug'
    | '/admin/bewild/new'
    | '/admin/conteudos/$slug'
    | '/admin/conteudos/novo'
    | '/admin/projetos/$slug'
    | '/admin/projetos/novo'
    | '/admin/seo/404'
    | '/admin/bewild/'
    | '/admin/conteudos/'
    | '/admin/projetos/'
    | '/admin/seo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessibilidade'
    | '/autorizacao-condominio'
    | '/como-funciona'
    | '/contato'
    | '/diagnostico'
    | '/escopo'
    | '/faq'
    | '/guia-do-investidor'
    | '/indique-um-amigo'
    | '/mapa'
    | '/mapa-do-site'
    | '/marcas-e-parcerias'
    | '/marcenaria'
    | '/o'
    | '/onde-atuamos'
    | '/orcamento'
    | '/p'
    | '/preferencias-de-cookies'
    | '/privacidade'
    | '/reforma-de-apartamento-sao-paulo'
    | '/reforma-de-cobertura-sao-paulo'
    | '/reforma-de-studio-sao-paulo'
    | '/servicos'
    | '/admin/analytics'
    | '/admin/central'
    | '/admin/conversoes'
    | '/admin/dashboard'
    | '/admin/diagnostico'
    | '/admin/faq'
    | '/admin/indexacao'
    | '/admin/indicacoes'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/lgpd'
    | '/admin/login'
    | '/admin/mensagens'
    | '/admin/orcamentos'
    | '/admin/qualificacao'
    | '/admin/rastreamento'
    | '/admin/settings'
    | '/admin/typography'
    | '/blog/$slug'
    | '/conteudos/$slug'
    | '/parceiros/incorporadoras'
    | '/portfolio/$slug'
    | '/reforma/$slug'
    | '/admin'
    | '/blog'
    | '/conteudos'
    | '/parceiros'
    | '/portfolio'
    | '/admin/bewild/$slug'
    | '/admin/bewild/new'
    | '/admin/conteudos/$slug'
    | '/admin/conteudos/novo'
    | '/admin/projetos/$slug'
    | '/admin/projetos/novo'
    | '/admin/seo/404'
    | '/admin/bewild'
    | '/admin/conteudos'
    | '/admin/projetos'
    | '/admin/seo'
  id:
    | '__root__'
    | '/'
    | '/acessibilidade'
    | '/autorizacao-condominio'
    | '/como-funciona'
    | '/contato'
    | '/diagnostico'
    | '/escopo'
    | '/faq'
    | '/guia-do-investidor'
    | '/indique-um-amigo'
    | '/mapa'
    | '/mapa-do-site'
    | '/marcas-e-parcerias'
    | '/marcenaria'
    | '/o'
    | '/onde-atuamos'
    | '/orcamento'
    | '/p'
    | '/preferencias-de-cookies'
    | '/privacidade'
    | '/reforma-de-apartamento-sao-paulo'
    | '/reforma-de-cobertura-sao-paulo'
    | '/reforma-de-studio-sao-paulo'
    | '/servicos'
    | '/admin/analytics'
    | '/admin/central'
    | '/admin/conversoes'
    | '/admin/dashboard'
    | '/admin/diagnostico'
    | '/admin/faq'
    | '/admin/indexacao'
    | '/admin/indicacoes'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/lgpd'
    | '/admin/login'
    | '/admin/mensagens'
    | '/admin/orcamentos'
    | '/admin/qualificacao'
    | '/admin/rastreamento'
    | '/admin/settings'
    | '/admin/typography'
    | '/blog/$slug'
    | '/conteudos/$slug'
    | '/parceiros/incorporadoras'
    | '/portfolio/$slug'
    | '/reforma/$slug'
    | '/admin/'
    | '/blog/'
    | '/conteudos/'
    | '/parceiros/'
    | '/portfolio/'
    | '/admin/bewild/$slug'
    | '/admin/bewild/new'
    | '/admin/conteudos/$slug'
    | '/admin/conteudos/novo'
    | '/admin/projetos/$slug'
    | '/admin/projetos/novo'
    | '/admin/seo/404'
    | '/admin/bewild/'
    | '/admin/conteudos/'
    | '/admin/projetos/'
    | '/admin/seo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessibilidadeRoute: typeof AcessibilidadeRoute
  AutorizacaoCondominioRoute: typeof AutorizacaoCondominioRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EscopoRoute: typeof EscopoRoute
  FaqRoute: typeof FaqRoute
  GuiaDoInvestidorRoute: typeof GuiaDoInvestidorRoute
  IndiqueUmAmigoRoute: typeof IndiqueUmAmigoRoute
  MapaRoute: typeof MapaRoute
  MapaDoSiteRoute: typeof MapaDoSiteRoute
  MarcasEParceriasRoute: typeof MarcasEParceriasRoute
  MarcenariaRoute: typeof MarcenariaRoute
  ORoute: typeof ORoute
  OndeAtuamosRoute: typeof OndeAtuamosRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PRoute: typeof PRoute
  PreferenciasDeCookiesRoute: typeof PreferenciasDeCookiesRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ReformaDeApartamentoSaoPauloRoute: typeof ReformaDeApartamentoSaoPauloRoute
  ReformaDeCoberturaSaoPauloRoute: typeof ReformaDeCoberturaSaoPauloRoute
  ReformaDeStudioSaoPauloRoute: typeof ReformaDeStudioSaoPauloRoute
  ServicosRoute: typeof ServicosRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCentralRoute: typeof AdminCentralRoute
  AdminConversoesRoute: typeof AdminConversoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDiagnosticoRoute: typeof AdminDiagnosticoRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminIndexacaoRoute: typeof AdminIndexacaoRoute
  AdminIndicacoesRoute: typeof AdminIndicacoesRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLgpdRoute: typeof AdminLgpdRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMensagensRoute: typeof AdminMensagensRoute
  AdminOrcamentosRoute: typeof AdminOrcamentosRoute
  AdminQualificacaoRoute: typeof AdminQualificacaoRoute
  AdminRastreamentoRoute: typeof AdminRastreamentoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTypographyRoute: typeof AdminTypographyRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ConteudosSlugRoute: typeof ConteudosSlugRoute
  ParceirosIncorporadorasRoute: typeof ParceirosIncorporadorasRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ReformaSlugRoute: typeof ReformaSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ConteudosIndexRoute: typeof ConteudosIndexRoute
  ParceirosIndexRoute: typeof ParceirosIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  AdminBewildSlugRoute: typeof AdminBewildSlugRoute
  AdminBewildNewRoute: typeof AdminBewildNewRoute
  AdminConteudosSlugRoute: typeof AdminConteudosSlugRoute
  AdminConteudosNovoRoute: typeof AdminConteudosNovoRoute
  AdminProjetosSlugRoute: typeof AdminProjetosSlugRoute
  AdminProjetosNovoRoute: typeof AdminProjetosNovoRoute
  AdminSeo404Route: typeof AdminSeo404Route
  AdminBewildIndexRoute: typeof AdminBewildIndexRoute
  AdminConteudosIndexRoute: typeof AdminConteudosIndexRoute
  AdminProjetosIndexRoute: typeof AdminProjetosIndexRoute
  AdminSeoIndexRoute: typeof AdminSeoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessibilidade': {
      id: '/acessibilidade'
      path: '/acessibilidade'
      fullPath: '/acessibilidade'
      preLoaderRoute: typeof AcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autorizacao-condominio': {
      id: '/autorizacao-condominio'
      path: '/autorizacao-condominio'
      fullPath: '/autorizacao-condominio'
      preLoaderRoute: typeof AutorizacaoCondominioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escopo': {
      id: '/escopo'
      path: '/escopo'
      fullPath: '/escopo'
      preLoaderRoute: typeof EscopoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-do-investidor': {
      id: '/guia-do-investidor'
      path: '/guia-do-investidor'
      fullPath: '/guia-do-investidor'
      preLoaderRoute: typeof GuiaDoInvestidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indique-um-amigo': {
      id: '/indique-um-amigo'
      path: '/indique-um-amigo'
      fullPath: '/indique-um-amigo'
      preLoaderRoute: typeof IndiqueUmAmigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-do-site': {
      id: '/mapa-do-site'
      path: '/mapa-do-site'
      fullPath: '/mapa-do-site'
      preLoaderRoute: typeof MapaDoSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas-e-parcerias': {
      id: '/marcas-e-parcerias'
      path: '/marcas-e-parcerias'
      fullPath: '/marcas-e-parcerias'
      preLoaderRoute: typeof MarcasEParceriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcenaria': {
      id: '/marcenaria'
      path: '/marcenaria'
      fullPath: '/marcenaria'
      preLoaderRoute: typeof MarcenariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o': {
      id: '/o'
      path: '/o'
      fullPath: '/o'
      preLoaderRoute: typeof ORouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-atuamos': {
      id: '/onde-atuamos'
      path: '/onde-atuamos'
      fullPath: '/onde-atuamos'
      preLoaderRoute: typeof OndeAtuamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferencias-de-cookies': {
      id: '/preferencias-de-cookies'
      path: '/preferencias-de-cookies'
      fullPath: '/preferencias-de-cookies'
      preLoaderRoute: typeof PreferenciasDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforma-de-apartamento-sao-paulo': {
      id: '/reforma-de-apartamento-sao-paulo'
      path: '/reforma-de-apartamento-sao-paulo'
      fullPath: '/reforma-de-apartamento-sao-paulo'
      preLoaderRoute: typeof ReformaDeApartamentoSaoPauloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforma-de-cobertura-sao-paulo': {
      id: '/reforma-de-cobertura-sao-paulo'
      path: '/reforma-de-cobertura-sao-paulo'
      fullPath: '/reforma-de-cobertura-sao-paulo'
      preLoaderRoute: typeof ReformaDeCoberturaSaoPauloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforma-de-studio-sao-paulo': {
      id: '/reforma-de-studio-sao-paulo'
      path: '/reforma-de-studio-sao-paulo'
      fullPath: '/reforma-de-studio-sao-paulo'
      preLoaderRoute: typeof ReformaDeStudioSaoPauloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/central': {
      id: '/admin/central'
      path: '/admin/central'
      fullPath: '/admin/central'
      preLoaderRoute: typeof AdminCentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conversoes': {
      id: '/admin/conversoes'
      path: '/admin/conversoes'
      fullPath: '/admin/conversoes'
      preLoaderRoute: typeof AdminConversoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostico': {
      id: '/admin/diagnostico'
      path: '/admin/diagnostico'
      fullPath: '/admin/diagnostico'
      preLoaderRoute: typeof AdminDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/admin/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/indexacao': {
      id: '/admin/indexacao'
      path: '/admin/indexacao'
      fullPath: '/admin/indexacao'
      preLoaderRoute: typeof AdminIndexacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/indicacoes': {
      id: '/admin/indicacoes'
      path: '/admin/indicacoes'
      fullPath: '/admin/indicacoes'
      preLoaderRoute: typeof AdminIndicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/admin/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lgpd': {
      id: '/admin/lgpd'
      path: '/admin/lgpd'
      fullPath: '/admin/lgpd'
      preLoaderRoute: typeof AdminLgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mensagens': {
      id: '/admin/mensagens'
      path: '/admin/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AdminMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orcamentos': {
      id: '/admin/orcamentos'
      path: '/admin/orcamentos'
      fullPath: '/admin/orcamentos'
      preLoaderRoute: typeof AdminOrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/qualificacao': {
      id: '/admin/qualificacao'
      path: '/admin/qualificacao'
      fullPath: '/admin/qualificacao'
      preLoaderRoute: typeof AdminQualificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rastreamento': {
      id: '/admin/rastreamento'
      path: '/admin/rastreamento'
      fullPath: '/admin/rastreamento'
      preLoaderRoute: typeof AdminRastreamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/typography': {
      id: '/admin/typography'
      path: '/admin/typography'
      fullPath: '/admin/typography'
      preLoaderRoute: typeof AdminTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/': {
      id: '/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos/'
      preLoaderRoute: typeof ConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/$slug': {
      id: '/conteudos/$slug'
      path: '/conteudos/$slug'
      fullPath: '/conteudos/$slug'
      preLoaderRoute: typeof ConteudosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros/': {
      id: '/parceiros/'
      path: '/parceiros'
      fullPath: '/parceiros/'
      preLoaderRoute: typeof ParceirosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros/incorporadoras': {
      id: '/parceiros/incorporadoras'
      path: '/parceiros/incorporadoras'
      fullPath: '/parceiros/incorporadoras'
      preLoaderRoute: typeof ParceirosIncorporadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reforma/$slug': {
      id: '/reforma/$slug'
      path: '/reforma/$slug'
      fullPath: '/reforma/$slug'
      preLoaderRoute: typeof ReformaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bewild/': {
      id: '/admin/bewild/'
      path: '/admin/bewild'
      fullPath: '/admin/bewild/'
      preLoaderRoute: typeof AdminBewildIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bewild/$slug': {
      id: '/admin/bewild/$slug'
      path: '/admin/bewild/$slug'
      fullPath: '/admin/bewild/$slug'
      preLoaderRoute: typeof AdminBewildSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bewild/new': {
      id: '/admin/bewild/new'
      path: '/admin/bewild/new'
      fullPath: '/admin/bewild/new'
      preLoaderRoute: typeof AdminBewildNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/': {
      id: '/admin/conteudos/'
      path: '/admin/conteudos'
      fullPath: '/admin/conteudos/'
      preLoaderRoute: typeof AdminConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/$slug': {
      id: '/admin/conteudos/$slug'
      path: '/admin/conteudos/$slug'
      fullPath: '/admin/conteudos/$slug'
      preLoaderRoute: typeof AdminConteudosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/novo': {
      id: '/admin/conteudos/novo'
      path: '/admin/conteudos/novo'
      fullPath: '/admin/conteudos/novo'
      preLoaderRoute: typeof AdminConteudosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projetos/': {
      id: '/admin/projetos/'
      path: '/admin/projetos'
      fullPath: '/admin/projetos/'
      preLoaderRoute: typeof AdminProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projetos/$slug': {
      id: '/admin/projetos/$slug'
      path: '/admin/projetos/$slug'
      fullPath: '/admin/projetos/$slug'
      preLoaderRoute: typeof AdminProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projetos/novo': {
      id: '/admin/projetos/novo'
      path: '/admin/projetos/novo'
      fullPath: '/admin/projetos/novo'
      preLoaderRoute: typeof AdminProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo/': {
      id: '/admin/seo/'
      path: '/admin/seo'
      fullPath: '/admin/seo/'
      preLoaderRoute: typeof AdminSeoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo/404': {
      id: '/admin/seo/404'
      path: '/admin/seo/404'
      fullPath: '/admin/seo/404'
      preLoaderRoute: typeof AdminSeo404RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessibilidadeRoute: AcessibilidadeRoute,
  AutorizacaoCondominioRoute: AutorizacaoCondominioRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EscopoRoute: EscopoRoute,
  FaqRoute: FaqRoute,
  GuiaDoInvestidorRoute: GuiaDoInvestidorRoute,
  IndiqueUmAmigoRoute: IndiqueUmAmigoRoute,
  MapaRoute: MapaRoute,
  MapaDoSiteRoute: MapaDoSiteRoute,
  MarcasEParceriasRoute: MarcasEParceriasRoute,
  MarcenariaRoute: MarcenariaRoute,
  ORoute: ORoute,
  OndeAtuamosRoute: OndeAtuamosRoute,
  OrcamentoRoute: OrcamentoRoute,
  PRoute: PRoute,
  PreferenciasDeCookiesRoute: PreferenciasDeCookiesRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ReformaDeApartamentoSaoPauloRoute: ReformaDeApartamentoSaoPauloRoute,
  ReformaDeCoberturaSaoPauloRoute: ReformaDeCoberturaSaoPauloRoute,
  ReformaDeStudioSaoPauloRoute: ReformaDeStudioSaoPauloRoute,
  ServicosRoute: ServicosRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCentralRoute: AdminCentralRoute,
  AdminConversoesRoute: AdminConversoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDiagnosticoRoute: AdminDiagnosticoRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminIndexacaoRoute: AdminIndexacaoRoute,
  AdminIndicacoesRoute: AdminIndicacoesRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLgpdRoute: AdminLgpdRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMensagensRoute: AdminMensagensRoute,
  AdminOrcamentosRoute: AdminOrcamentosRoute,
  AdminQualificacaoRoute: AdminQualificacaoRoute,
  AdminRastreamentoRoute: AdminRastreamentoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTypographyRoute: AdminTypographyRoute,
  BlogSlugRoute: BlogSlugRoute,
  ConteudosSlugRoute: ConteudosSlugRoute,
  ParceirosIncorporadorasRoute: ParceirosIncorporadorasRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ReformaSlugRoute: ReformaSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ConteudosIndexRoute: ConteudosIndexRoute,
  ParceirosIndexRoute: ParceirosIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  AdminBewildSlugRoute: AdminBewildSlugRoute,
  AdminBewildNewRoute: AdminBewildNewRoute,
  AdminConteudosSlugRoute: AdminConteudosSlugRoute,
  AdminConteudosNovoRoute: AdminConteudosNovoRoute,
  AdminProjetosSlugRoute: AdminProjetosSlugRoute,
  AdminProjetosNovoRoute: AdminProjetosNovoRoute,
  AdminSeo404Route: AdminSeo404Route,
  AdminBewildIndexRoute: AdminBewildIndexRoute,
  AdminConteudosIndexRoute: AdminConteudosIndexRoute,
  AdminProjetosIndexRoute: AdminProjetosIndexRoute,
  AdminSeoIndexRoute: AdminSeoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
